/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCard: typeof import('./components/Activities/ActivityCard.vue')['default']
    AllDaysActivities: typeof import('./components/Activities/AllDaysActivities.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppGuestTitle: typeof import('./components/AppGuestTitle.vue')['default']
    DailyNotes: typeof import('./components/Home/DailyNotes.vue')['default']
    DayCard: typeof import('./components/DayCard.vue')['default']
    GeneralProgress: typeof import('./components/Home/GeneralProgress.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NextDayActivities: typeof import('./components/Activities/NextDayActivities.vue')['default']
    NextDayRoutines: typeof import('./components/Activities/NextDayRoutines.vue')['default']
    ProfileActions: typeof import('./components/Profile/ProfileActions.vue')['default']
    ProfilePicture: typeof import('./components/Profile/ProfilePicture.vue')['default']
    QuickAccess: typeof import('./components/Home/QuickAccess.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutineList: typeof import('./components/RoutineList.vue')['default']
    SignInForm: typeof import('./components/SignInForm.vue')['default']
    'SignInForm.1': typeof import('./components/SignInForm.1.vue')['default']
    SignUpForm: typeof import('./components/SignUpForm.vue')['default']
    Starter: typeof import('./components/Starter.vue')['default']
    TodayActivities: typeof import('./components/Home/TodayActivities.vue')['default']
    Welcome: typeof import('./components/Welcome.vue')['default']
  }
}
