/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Welcome': RouteRecordInfo<'Welcome', '/', Record<never, never>, Record<never, never>>,
    'Home': RouteRecordInfo<'Home', '/home', Record<never, never>, Record<never, never>>,
    'Profile': RouteRecordInfo<'Profile', '/profile', Record<never, never>, Record<never, never>>,
    'Routines': RouteRecordInfo<'Routines', '/routines', Record<never, never>, Record<never, never>>,
    'Routine Details': RouteRecordInfo<'Routine Details', '/routines/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'New Activity': RouteRecordInfo<'New Activity', '/routines/new', Record<never, never>, Record<never, never>>,
    'Settings': RouteRecordInfo<'Settings', '/settings', Record<never, never>, Record<never, never>>,
    'SignIn': RouteRecordInfo<'SignIn', '/signin', Record<never, never>, Record<never, never>>,
    'SignUp': RouteRecordInfo<'SignUp', '/signup', Record<never, never>, Record<never, never>>,
  }
}
